/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfas_alumno;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author liooficial
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
        
        rsscalelabel.RSScaleLabel.setScaleLabel(jLabel_candadoImagen,"src/img/candado.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(jLabel_iscImagen,"src/img/isc.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(jLabel_logoImagen,"src/img/logo.png");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel_elementos = new javax.swing.JPanel();
        btn_ingreso = new javax.swing.JButton();
        txtfid_contraseña = new javax.swing.JPasswordField();
        TextField_usuario = new javax.swing.JTextField();
        jlabel_acceso = new javax.swing.JLabel();
        jLabel_usuario = new javax.swing.JLabel();
        jLabel_contraseña = new javax.swing.JLabel();
        CheckBox_mostrarContraseña = new javax.swing.JCheckBox();
        jLabel_candadoImagen = new javax.swing.JLabel();
        jpanel_imagenes = new javax.swing.JPanel();
        jLabel_iscImagen = new javax.swing.JLabel();
        jLabel_principalImagen = new javax.swing.JLabel();
        jLabel_logoImagen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setEnabled(false);
        setExtendedState(2);

        jPanel1.setBackground(new java.awt.Color(23, 23, 23));
        jPanel1.setForeground(new java.awt.Color(23, 23, 23));

        jPanel_elementos.setBackground(new java.awt.Color(27, 27, 27));

        btn_ingreso.setBackground(new java.awt.Color(101, 0, 11));
        btn_ingreso.setFont(new java.awt.Font("Century Schoolbook", 0, 15)); // NOI18N
        btn_ingreso.setText("INGRESAR");
        btn_ingreso.setBorder(null);

        txtfid_contraseña.setText("jPasswordField1");

        TextField_usuario.setText("...");

        jlabel_acceso.setFont(new java.awt.Font("Arial Black", 0, 21)); // NOI18N
        jlabel_acceso.setForeground(new java.awt.Color(255, 255, 255));
        jlabel_acceso.setText("Acceso");

        jLabel_usuario.setFont(new java.awt.Font("Bell MT", 0, 14)); // NOI18N
        jLabel_usuario.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_usuario.setText("USUARIO:");

        jLabel_contraseña.setFont(new java.awt.Font("Bell MT", 0, 14)); // NOI18N
        jLabel_contraseña.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_contraseña.setText("CONTRASEÑA:");

        CheckBox_mostrarContraseña.setBackground(new java.awt.Color(27, 27, 27));
        CheckBox_mostrarContraseña.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
        CheckBox_mostrarContraseña.setForeground(new java.awt.Color(255, 255, 255));
        CheckBox_mostrarContraseña.setText("MOSTRAR");
        CheckBox_mostrarContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBox_mostrarContraseñaActionPerformed(evt);
            }
        });

        jLabel_candadoImagen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 255, 255)));

        javax.swing.GroupLayout jPanel_elementosLayout = new javax.swing.GroupLayout(jPanel_elementos);
        jPanel_elementos.setLayout(jPanel_elementosLayout);
        jPanel_elementosLayout.setHorizontalGroup(
            jPanel_elementosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_elementosLayout.createSequentialGroup()
                .addGroup(jPanel_elementosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_elementosLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanel_elementosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CheckBox_mostrarContraseña)
                            .addGroup(jPanel_elementosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel_contraseña)
                                .addComponent(jLabel_usuario)
                                .addComponent(txtfid_contraseña, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                                .addComponent(TextField_usuario))))
                    .addGroup(jPanel_elementosLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(btn_ingreso, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_elementosLayout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addGroup(jPanel_elementosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel_candadoImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlabel_acceso))))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel_elementosLayout.setVerticalGroup(
            jPanel_elementosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_elementosLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jlabel_acceso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel_candadoImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(jLabel_usuario)
                .addGap(18, 18, 18)
                .addComponent(TextField_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel_contraseña)
                .addGap(18, 18, 18)
                .addComponent(txtfid_contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(CheckBox_mostrarContraseña)
                .addGap(18, 18, 18)
                .addComponent(btn_ingreso, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
        );

        jpanel_imagenes.setBackground(new java.awt.Color(27, 27, 27));

        jLabel_iscImagen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 255, 255)));

        jLabel_principalImagen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 255, 255)));

        jLabel_logoImagen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 255, 255)));

        javax.swing.GroupLayout jpanel_imagenesLayout = new javax.swing.GroupLayout(jpanel_imagenes);
        jpanel_imagenes.setLayout(jpanel_imagenesLayout);
        jpanel_imagenesLayout.setHorizontalGroup(
            jpanel_imagenesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel_imagenesLayout.createSequentialGroup()
                .addComponent(jLabel_iscImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 171, Short.MAX_VALUE))
            .addComponent(jLabel_logoImagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel_principalImagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpanel_imagenesLayout.setVerticalGroup(
            jpanel_imagenesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel_imagenesLayout.createSequentialGroup()
                .addComponent(jLabel_iscImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_principalImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(jLabel_logoImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jpanel_imagenes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                .addComponent(jPanel_elementos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel_elementos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpanel_imagenes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(84, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CheckBox_mostrarContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBox_mostrarContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CheckBox_mostrarContraseñaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CheckBox_mostrarContraseña;
    private javax.swing.JTextField TextField_usuario;
    private javax.swing.JButton btn_ingreso;
    private javax.swing.JLabel jLabel_candadoImagen;
    private javax.swing.JLabel jLabel_contraseña;
    private javax.swing.JLabel jLabel_iscImagen;
    private javax.swing.JLabel jLabel_logoImagen;
    private javax.swing.JLabel jLabel_principalImagen;
    private javax.swing.JLabel jLabel_usuario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel_elementos;
    private javax.swing.JLabel jlabel_acceso;
    private javax.swing.JPanel jpanel_imagenes;
    private javax.swing.JPasswordField txtfid_contraseña;
    // End of variables declaration//GEN-END:variables

    private void setLocationRelativeto(login aThis) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
