/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfas_alumno;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author liooficial
 */
public class Reportes extends javax.swing.JFrame {

    /**
     * Creates new form Inventario
     */
    public Reportes() {
        initComponents(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pn_principal = new javax.swing.JPanel();
        pn_menuLateral = new javax.swing.JPanel();
        pn_rojo = new javax.swing.JPanel();
        lb_usuario = new javax.swing.JLabel();
        lb_nombreDelUsuario = new javax.swing.JLabel();
        lb_usuarioImg = new javax.swing.JLabel();
        lb_administrarImg = new javax.swing.JLabel();
        lb_logoImg = new javax.swing.JLabel();
        lb_administrarUsuarioImg = new javax.swing.JLabel();
        lb_reportesimg = new javax.swing.JLabel();
        lb_rondinesimg = new javax.swing.JLabel();
        lb_notificacionesimg = new javax.swing.JLabel();
        lb_invetaimg = new javax.swing.JLabel();
        bt_administrar_Horarios = new javax.swing.JToggleButton();
        bt_administrar_Usuarios = new javax.swing.JToggleButton();
        bt_rondines = new javax.swing.JToggleButton();
        bt_inventario = new javax.swing.JToggleButton();
        bt_notificaciones = new javax.swing.JToggleButton();
        bt_reportes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pn_principal.setBackground(new java.awt.Color(255, 255, 255));

        pn_menuLateral.setBackground(new java.awt.Color(255, 255, 255));
        pn_menuLateral.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pn_rojo.setBackground(new java.awt.Color(107, 8, 48));
        pn_rojo.setForeground(new java.awt.Color(255, 0, 153));

        lb_usuario.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lb_usuario.setForeground(new java.awt.Color(255, 255, 255));
        lb_usuario.setText("usuario:");

        lb_nombreDelUsuario.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lb_nombreDelUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lb_nombreDelUsuario.setText("Administrador");

        lb_usuarioImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/administrador.png"))); // NOI18N

        javax.swing.GroupLayout pn_rojoLayout = new javax.swing.GroupLayout(pn_rojo);
        pn_rojo.setLayout(pn_rojoLayout);
        pn_rojoLayout.setHorizontalGroup(
            pn_rojoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_rojoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_usuarioImg, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pn_rojoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_rojoLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(lb_usuario))
                    .addGroup(pn_rojoLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lb_nombreDelUsuario)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pn_rojoLayout.setVerticalGroup(
            pn_rojoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_rojoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lb_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lb_nombreDelUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
            .addGroup(pn_rojoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_usuarioImg, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pn_menuLateral.add(pn_rojo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 600, 350, 160));

        lb_administrarImg.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_administrarImg.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pn_menuLateral.add(lb_administrarImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 70, 40));

        lb_logoImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/isc350X140.png"))); // NOI18N
        pn_menuLateral.add(lb_logoImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 140));

        lb_administrarUsuarioImg.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_administrarUsuarioImg.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pn_menuLateral.add(lb_administrarUsuarioImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 70, 40));

        lb_reportesimg.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_reportesimg.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pn_menuLateral.add(lb_reportesimg, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 70, 40));

        lb_rondinesimg.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_rondinesimg.setText(" ");
        lb_rondinesimg.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pn_menuLateral.add(lb_rondinesimg, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 70, 40));

        lb_notificacionesimg.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_notificacionesimg.setText(" ");
        lb_notificacionesimg.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pn_menuLateral.add(lb_notificacionesimg, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, 70, 40));

        lb_invetaimg.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_invetaimg.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pn_menuLateral.add(lb_invetaimg, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 520, 70, 40));

        bt_administrar_Horarios.setBackground(new java.awt.Color(255, 255, 255));
        bt_administrar_Horarios.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bt_administrar_Horarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/calendario60X60.png"))); // NOI18N
        bt_administrar_Horarios.setText("   Administrar horarios");
        bt_administrar_Horarios.setBorder(null);
        bt_administrar_Horarios.setContentAreaFilled(false);
        bt_administrar_Horarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_administrar_Horarios.setFocusPainted(false);
        bt_administrar_Horarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_administrar_HorariosActionPerformed(evt);
            }
        });
        pn_menuLateral.add(bt_administrar_Horarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 350, 60));

        bt_administrar_Usuarios.setBackground(new java.awt.Color(204, 204, 204));
        bt_administrar_Usuarios.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bt_administrar_Usuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/grupo-de-usuarios60X60.png"))); // NOI18N
        bt_administrar_Usuarios.setText("   Administrar usuarios");
        bt_administrar_Usuarios.setContentAreaFilled(false);
        bt_administrar_Usuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_administrar_Usuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_administrar_UsuariosActionPerformed(evt);
            }
        });
        pn_menuLateral.add(bt_administrar_Usuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 350, 60));

        bt_rondines.setBackground(new java.awt.Color(255, 255, 255));
        bt_rondines.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bt_rondines.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ronda60X60.png"))); // NOI18N
        bt_rondines.setText("Rondines                   ");
        bt_rondines.setContentAreaFilled(false);
        bt_rondines.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_rondines.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_rondinesActionPerformed(evt);
            }
        });
        pn_menuLateral.add(bt_rondines, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 350, 60));

        bt_inventario.setBackground(new java.awt.Color(255, 255, 255));
        bt_inventario.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bt_notificaciones.setContentAreaFilled(false);
        bt_inventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/inventario60X60.png"))); // NOI18N
        bt_inventario.setText(" Inventario                ");
        bt_inventario.setBorder(null);
        bt_inventario.setBorderPainted(false);
        bt_inventario.setContentAreaFilled(false);
        bt_inventario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_inventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_inventarioActionPerformed(evt);
            }
        });
        pn_menuLateral.add(bt_inventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 510, 350, 60));

        bt_notificaciones.setBackground(new java.awt.Color(255, 255, 255));
        bt_notificaciones.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bt_notificaciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/correo60X60.png"))); // NOI18N
        bt_notificaciones.setText("Notificaciones             ");
        bt_notificaciones.setContentAreaFilled(false);
        bt_notificaciones.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_notificaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_notificacionesActionPerformed(evt);
            }
        });
        pn_menuLateral.add(bt_notificaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 350, 60));

        bt_reportes.setBackground(new java.awt.Color(204, 204, 204));
        bt_reportes.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bt_reportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/reporte2_60X60.png"))); // NOI18N
        bt_reportes.setText("Reportes                     ");
        bt_reportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_reportesActionPerformed(evt);
            }
        });
        pn_menuLateral.add(bt_reportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 360, 59));

        javax.swing.GroupLayout pn_principalLayout = new javax.swing.GroupLayout(pn_principal);
        pn_principal.setLayout(pn_principalLayout);
        pn_principalLayout.setHorizontalGroup(
            pn_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_principalLayout.createSequentialGroup()
                .addComponent(pn_menuLateral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1004, Short.MAX_VALUE))
        );
        pn_principalLayout.setVerticalGroup(
            pn_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_principalLayout.createSequentialGroup()
                .addComponent(pn_menuLateral, javax.swing.GroupLayout.PREFERRED_SIZE, 762, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_administrar_HorariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_administrar_HorariosActionPerformed
        Administrar_horario2 ventana = new Administrar_horario2( );
                ventana.setVisible(true);
                this.setVisible(false);
    }//GEN-LAST:event_bt_administrar_HorariosActionPerformed

    private void bt_administrar_UsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_administrar_UsuariosActionPerformed

    }//GEN-LAST:event_bt_administrar_UsuariosActionPerformed

    private void bt_rondinesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_rondinesActionPerformed
       Rondines ventana = new Rondines( );
                ventana.setVisible(true);
                this.setVisible(false);
    }//GEN-LAST:event_bt_rondinesActionPerformed

    private void bt_notificacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_notificacionesActionPerformed

    }//GEN-LAST:event_bt_notificacionesActionPerformed

    private void bt_inventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_inventarioActionPerformed
        Inventario ventana = new Inventario( );
                ventana.setVisible(true);
                this.setVisible(false);
    }//GEN-LAST:event_bt_inventarioActionPerformed

    private void bt_reportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_reportesActionPerformed
        Reportes ventana = new Reportes( );
                ventana.setVisible(true);
                this.setVisible(false);
    }//GEN-LAST:event_bt_reportesActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reportes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton bt_administrar_Horarios;
    private javax.swing.JToggleButton bt_administrar_Usuarios;
    private javax.swing.JToggleButton bt_inventario;
    private javax.swing.JToggleButton bt_notificaciones;
    private javax.swing.JButton bt_reportes;
    private javax.swing.JToggleButton bt_rondines;
    private javax.swing.JLabel lb_administrarImg;
    private javax.swing.JLabel lb_administrarUsuarioImg;
    private javax.swing.JLabel lb_invetaimg;
    private javax.swing.JLabel lb_logoImg;
    private javax.swing.JLabel lb_nombreDelUsuario;
    private javax.swing.JLabel lb_notificacionesimg;
    private javax.swing.JLabel lb_reportesimg;
    private javax.swing.JLabel lb_rondinesimg;
    private javax.swing.JLabel lb_usuario;
    private javax.swing.JLabel lb_usuarioImg;
    private javax.swing.JPanel pn_menuLateral;
    private javax.swing.JPanel pn_principal;
    private javax.swing.JPanel pn_rojo;
    // End of variables declaration//GEN-END:variables
}
